package com.myspace.solicitacaodecotacaologin;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequisitarSolicitacao implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Equipamento")
	private java.lang.String equipamento;
	@org.kie.api.definition.type.Label(value = "Regiao")
	private java.lang.String regiao;
	@org.kie.api.definition.type.Label(value = "Cidade Origem")
	private java.lang.String cidadeOrigem;
	@org.kie.api.definition.type.Label(value = "UF Origem")
	private java.lang.String ufOrigem;
	@org.kie.api.definition.type.Label(value = "Cidade Destino")
	private java.lang.String cidadeDestino;
	@org.kie.api.definition.type.Label(value = "UF Destino")
	private java.lang.String ufDestino;
	@org.kie.api.definition.type.Label(value = "KM")
	private int KM;
	@org.kie.api.definition.type.Label(value = "Carreta")
	private java.lang.String carreta;
	@org.kie.api.definition.type.Label(value = "Frete")
	private double frete;
	@org.kie.api.definition.type.Label(value = "Pedagio (Ida e Volta)")
	private double pedagio;
	@org.kie.api.definition.type.Label(value = "Tipo de Imposto")
	private java.lang.String tipoImposto;
	@org.kie.api.definition.type.Label(value = "Aliquota (%)")
	private double aliquota;

	public RequisitarSolicitacao() {
	}

	public java.lang.String getEquipamento() {
		return this.equipamento;
	}

	public void setEquipamento(java.lang.String equipamento) {
		this.equipamento = equipamento;
	}

	public java.lang.String getRegiao() {
		return this.regiao;
	}

	public void setRegiao(java.lang.String regiao) {
		this.regiao = regiao;
	}

	public java.lang.String getCidadeOrigem() {
		return this.cidadeOrigem;
	}

	public void setCidadeOrigem(java.lang.String cidadeOrigem) {
		this.cidadeOrigem = cidadeOrigem;
	}

	public java.lang.String getUfOrigem() {
		return this.ufOrigem;
	}

	public void setUfOrigem(java.lang.String ufOrigem) {
		this.ufOrigem = ufOrigem;
	}

	public java.lang.String getCidadeDestino() {
		return this.cidadeDestino;
	}

	public void setCidadeDestino(java.lang.String cidadeDestino) {
		this.cidadeDestino = cidadeDestino;
	}

	public java.lang.String getUfDestino() {
		return this.ufDestino;
	}

	public void setUfDestino(java.lang.String ufDestino) {
		this.ufDestino = ufDestino;
	}

	public int getKM() {
		return this.KM;
	}

	public void setKM(int KM) {
		this.KM = KM;
	}

	public java.lang.String getCarreta() {
		return this.carreta;
	}

	public void setCarreta(java.lang.String carreta) {
		this.carreta = carreta;
	}

	public double getFrete() {
		return this.frete;
	}

	public void setFrete(double frete) {
		this.frete = frete;
	}

	public double getPedagio() {
		return this.pedagio;
	}

	public void setPedagio(double pedagio) {
		this.pedagio = pedagio;
	}

	public java.lang.String getTipoImposto() {
		return this.tipoImposto;
	}

	public void setTipoImposto(java.lang.String tipoImposto) {
		this.tipoImposto = tipoImposto;
	}

	public double getAliquota() {
		return this.aliquota;
	}

	public void setAliquota(double aliquota) {
		this.aliquota = aliquota;
	}

	public RequisitarSolicitacao(java.lang.String equipamento,
			java.lang.String regiao, java.lang.String cidadeOrigem,
			java.lang.String ufOrigem, java.lang.String cidadeDestino,
			java.lang.String ufDestino, int KM, java.lang.String carreta,
			double frete, double pedagio, java.lang.String tipoImposto,
			double aliquota) {
		this.equipamento = equipamento;
		this.regiao = regiao;
		this.cidadeOrigem = cidadeOrigem;
		this.ufOrigem = ufOrigem;
		this.cidadeDestino = cidadeDestino;
		this.ufDestino = ufDestino;
		this.KM = KM;
		this.carreta = carreta;
		this.frete = frete;
		this.pedagio = pedagio;
		this.tipoImposto = tipoImposto;
		this.aliquota = aliquota;
	}

}